import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

const XHS_BASE_URL = 'https://adapi.xiaohongshu.com';
const XHS_OAUTH_BASE = 'https://adapi.xiaohongshu.com/oauth2';
const XHS_BINDING_URL = 'https://ad.xiaohongshu.com/api/leona/three/im/account/add';

interface SendMessageParams {
  userId: string;
  requestId: string;
  messageType: string;
  fromUserId: string;
  toUserId: string;
  thirdAccountId: string;
  timestamp: number;
  contentEncrypted: string;
}

@Injectable()
export class XhsApiClient {
  private readonly logger = new Logger(XhsApiClient.name);
  private readonly defaultAccessToken: string;
  private readonly appId: string;
  private readonly appSecret: string;

  constructor(private configService: ConfigService) {
    this.defaultAccessToken = this.configService.get<string>('XHS_ACCESS_TOKEN', '');
    this.appId = this.configService.get<string>('XHS_APP_ID', '');
    this.appSecret = this.configService.get<string>('XHS_APP_SECRET', '');
  }

  /**
   * Generate OAuth authorization URL for QR code scanning.
   * User scans → authorizes → redirected to redirectUri with ?code=xxx&state=xxx
   */
  getAuthUrl(redirectUri: string, state: string): string {
    const params = new URLSearchParams({
      app_id: this.appId,
      redirect_uri: redirectUri,
      state,
      response_type: 'code',
      scope: 'im',
    });
    return `${XHS_OAUTH_BASE}/authorize?${params.toString()}`;
  }

  /**
   * Generate the documented Juguang third-party account binding URL.
   * The token is generated by our platform and must contain account_code after decryption.
   */
  getBindingUrl(token: string): string {
    const params = new URLSearchParams({
      appId: this.appId,
      token,
    });
    return `${XHS_BINDING_URL}?${params.toString()}`;
  }

  /**
   * Exchange authorization code for access token + account info.
   * Returns: { access_token, user_id, third_account_id, nick_name, expires_in, ... }
   */
  async exchangeCode(code: string): Promise<{
    access_token: string;
    user_id: string;
    third_account_id: string;
    nick_name?: string;
    expires_in?: number;
    token_type?: string;
  }> {
    const resp = await fetch(`${XHS_OAUTH_BASE}/access_token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        app_id: this.appId,
        app_secret: this.appSecret,
        code,
        grant_type: 'authorization_code',
      }),
    });

    if (!resp.ok) {
      const text = await resp.text().catch(() => '');
      this.logger.error(`XHS OAuth token exchange failed: ${resp.status} ${text}`);
      throw new Error(`XHS OAuth error: ${resp.status}`);
    }

    const data = await resp.json() as any;
    if (data.code !== 0 && data.code !== 200) {
      this.logger.error(`XHS OAuth business error: ${JSON.stringify(data)}`);
      throw new Error(data.msg || data.message || 'OAuth token exchange failed');
    }

    return data.data || data;
  }

  async sendMessage(params: SendMessageParams, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/third/send', {
      user_id: params.userId,
      request_id: params.requestId,
      message_type: params.messageType,
      from_user_id: params.fromUserId,
      to_user_id: params.toUserId,
      third_account_id: params.thirdAccountId,
      timestamp: params.timestamp,
      'content-encrypted': params.contentEncrypted,
    }, accessToken);
  }

  async queryKosAccounts(userId: string, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/auth/bind_users', { user_id: userId }, accessToken);
  }

  async bindAccount(params: { userId: string; nickName: string; token: string }, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/third/bind_account', {
      user_id: params.userId,
      nick_name: params.nickName,
      token: params.token,
    }, accessToken);
  }

  async unbindAccount(params: { userId: string; thirdAccountId: string }, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/third/unbind_account', {
      user_id: params.userId,
      third_account_id: params.thirdAccountId,
    }, accessToken);
  }

  async queryLandingPages(params: { pageNo: number; pageSize: number }, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/page/list', params, accessToken);
  }

  async queryMaterials(params: { type: number; pageNo: number; pageSize: number }, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/material/list', params, accessToken);
  }

  async queryNotes(params: { pageNo: number; pageSize: number }, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/note/list', params, accessToken);
  }

  async queryComments(params: { noteId: string; pageNo: number; pageSize: number }, accessToken?: string): Promise<any> {
    return this.post('/api/open/im/comment/list', params, accessToken);
  }

  private async post(path: string, body: Record<string, any>, accessToken?: string): Promise<any> {
    const token = accessToken || this.defaultAccessToken;
    const url = `${XHS_BASE_URL}${path}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Access-Token': token,
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const text = await response.text().catch(() => '');
      this.logger.error(`XHS API ${path} failed: ${response.status} ${text}`);
      throw new Error(`XHS API error: ${response.status}`);
    }

    const data = await response.json();
    if (data.code !== 0 && data.code !== 200) {
      this.logger.error(`XHS API ${path} business error: ${JSON.stringify(data)}`);
      throw new Error(`XHS API business error: ${data.msg || data.message || 'unknown'}`);
    }

    return data;
  }
}
